# SCW_API_KEY='XXX' ansible-playbook ./test/legacy/scaleway_compute.yml
- name: Deploy a server for ARK Survival
  hosts: localhost
  gather_facts: no
  environment:
    #    SCW_API_KEY: ""
  tasks:
  - name: Run it
    scaleway_compute:
      name: ark-test
      state: running
      image: da6ebdf0-cb8f-4c5b-92cd-fd3a6929f75d
      organization: c3d0141f-ab1a-47e2-84bb-6652a7f640be
      region: par1
      commercial_type: VC1S
      wait: true
      tags:
        - test
        - ark
        - gaming


