# SCW_API_KEY='XXX' ansible-playbook deploy_ark.yml
- name: Deploy a server for ARK Survival
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Deploy server and launch it
    include: tasks/provision.yml server_name={{item}}
    with_items:
      - manny


