# SCW_API_KEY='XXX' ansible-playbook setup_ark.yml -i scaleway_inventory.yml
- name: Deploy a server for ARK Survival
  hosts: ark
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Add non-free packages repository
      template:
        src: sources.list
        dest: /etc/apt/sources.list
    - name: Add i386 package
      command: dpkg --add-architecture i386
    - name: Accept Steam license
      debconf:
        name: steamcmd
        question: steam/question
        value: 'I AGREE'
        vtype: select
    - name: Create steam user
      user:
        name: steam
        comment: For running steam apps
        generate_ssh_key: no
    - name: Update repositories cache and install steam package
      apt:
        update_cache: yes
        name: steamcmd:i386
    - name: Install dependencies for ark-server-tools
      apt:
        update_cache: no
        name: "{{ packages }}"
      vars:
        packages:
          - perl-modules
          - curl
          - lsof
          - libc6-i386
          - lib32gcc1
          - bzip2
    - name: Download Ark Manager setup
      get_url:
        url: https://raw.githubusercontent.com/FezVrasta/ark-server-tools/master/netinstall.sh
        dest: /tmp/install_arkmanager.sh
    - name: Install Ark Manager
      command: bash /tmp/install_arkmanager.sh steam
      args:
        creates: /etc/arkmanager/arkmanager.cfg
    - name: Install ARK Survival From Steam
      command: arkmanager install
      args:
        creates: /home/steam/ARK
    - name: Copy arkmanager instance config
      template:
        src: manny.cfg.j2
        dest: /etc/arkmanager/instances/manny.cfg
    - name: Ensures ARK conf dir
      become_user: steam
      file:
        path: /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer
        state: directory
    - name: Copy ARK config Game.ini
      template:
        src: Game.ini.j2
        dest: /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/Game.ini
    - name: Copy ARK config GameUserSettings.ini
      template:
        src: GameUserSettings.ini.j2
        dest: /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
